### PR TITLE
Add Faithlife.Analyzers

### PR DESCRIPTION
**Pull request by bgrainger**
Merge in all the updated C# Template changes and fix the analyzer warnings that were encountered.

### CODE REVIEW

**Comment by david-mitchell** [comment]
Looks like the mono build is failing because the Analyzer package can’t access Microsoft.CodeAnalysis during load.

**Comment by bgrainger** [comment]
Sounds like it might be related to the VS version that's installed: https://stackoverflow.com/a/45680699

I presume a similar problem could exist for Mono. Downgrading the required version of `Microsoft.CodeAnalysis.CSharp.Workspaces` in the analyzer might make it more compatible. I wonder if there's a changelog that could help us decide.

**Comment by bgrainger** [comment]
https://github.com/dotnet/roslyn/wiki/NuGet-packages#versioning

**Comment by bgrainger** [comment]
I might downgrade to 2.7.0 (C# 7.2 and VB 15.5, but with a number of fixes); presumably we can't write analyzers that detect/use C# 7.3 features, but the analyzer would still work in a project that used that language version.

**Pull request merged**
