### PR TITLE
Format with dotnet-format

### PR DESCRIPTION
**Pull request by ddunkin**

### CODE REVIEW

**Comment by ejball** [comment]
What is `dotnet-format`?

**Comment by bgrainger** [comment]
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#dotnet-format, presumably.

**Comment by ddunkin** [comment]
Right, it's a part of Roslyn 3.0. https://github.com/dotnet/roslyn/blob/master/src/Tools/dotnet-format/README.md

**Comment by ddunkin** [comment]
Now in it's own repo: https://github.com/dotnet/format/

**Pull request merged**
